### ISSUE TITLE
Changes to /lz/ directory structure

### ISSUE THREAD

**Issue by rob-tay** [alexanderrichards/LZProduction#112]
Proposed structure, still needs fleshing out. Will require the database to handle the links between different parts of production chain. E.g each part of chain has a parent/child id that links to previous part 

/lz/data/    	 		- real system data

/lz/simulation/ 		- LUXSim/BACCARAT/DER Output
	E.g /BACCARAT-{version}-geant4.{version}/DER-{version}/{macro_name}
(Do we even need the nested directories if information is available in database?)
	
/lz/lzap/				- TDRAnalysis/LZap Output*      
(How do we identify rqs from data vs simulation? Through the database? )
		E.g /LZap-{version}/Physics-{version}/{macro_name}
	
/lz/test/			- temp space for test jobs/processing

**Comment by alexanderrichards** [comment]
closing this as the new interface allows the user to specify the output LFN structure with the job which I think addresses these concerns
