### ISSUE TITLE
Add site dropdown to new requests

### ISSUE THREAD

**Issue by alexanderrichards** [alexanderrichards/LZProduction#121]
Add a dropdown selection of site to run at to the new requests page. options should be any or IC

**Comment by sfayer** [comment]
Hi Alex,

Would it be possible to push this up the todo list a bit? The jobs are well under-way now, but we're still not getting many pilots at IC...

Regards,
Simon

**Comment by alexanderrichards** [comment]
absolutely, It's the next thing to do. I had to fix the problem of it not working as a priority 😉 I think that it is doing now so I'll be on this first thing next week

________________________________
