### ISSUE TITLE
Add support for job priorities

### ISSUE THREAD

**Issue by sfayer** [alexanderrichards/LZProduction#191]
Hi,

At the last review, we were asked whether it was possible to set relative job priorities so that a normal user couldn't accidentally swamp out important production with their own jobs.

DIRAC JDL (and other interfaces) has an option to set a Priority. The field is literally just called "Priority" and takes an integer in the range 0..10, it defaults to 1 if unset. Larger numbers are higher priorities.

My suggestion would be to add a field to the request page which passes this value through, defaulting to 3 or something like that. That way particularly important production (MDC2?) can be run with a higher value. (I guess the exact behaviour should be up to LZ people).

Regards,
Simon

**Comment by alexanderrichards** [comment]
Hi Simon,
Thanks, this is a relatively minor change. I'll do this when I'm back on Tuesday.

Cheers
Alex
________________________________

**Comment by alexanderrichards** [comment]
I have implemented this as described in your request, namely priority in range [0,10) defaulting to 3. I had to use an internal method of the API (eww) as they didn't provide a public one. Lets see if it works.
