### ISSUE TITLE
Requests with multiple macros

### ISSUE THREAD

**Issue by rob-tay** [alexanderrichards/LZProduction#91]
Requests with multiple macros selected are not being adding to the requests table

**Comment by alexanderrichards** [comment]
They will be in the parametric jobs table, each macro is a parametric job.

**Comment by rob-tay** [comment]
Sorry should have been more specific. Creating a new request with multiple macros selected does not result in that request being added to the either the parametricjobs or requests table.

**Comment by alexanderrichards** [comment]
ah ok. then this is a bug. I'll look into it right away
