### ISSUE TITLE
Macro search only matches beginning of string

### ISSUE THREAD

**Issue by rob-tay** [alexanderrichards/LZProduction#92]
E.g searching 'tpc' does not match any macro

**Comment by alexanderrichards** [comment]
This is by design, it performs a starts with style search. would you prefer a contains?

**Comment by rob-tay** [comment]
I think that would be better as it allows for searching for a specific source/component, which are generally in the middle/end of the macro name

**Comment by alexanderrichards** [comment]
right o, simple fix.
